version: "3"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
             - "4001:3000"
        volumes:
            - .:/app
            - /app/node_modules
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]